// automatically generated by the FlatBuffers compiler, do not modify

namespace InWorldz.Arbiter.Serialization
{

public enum HollowShape : sbyte
{
 Same = 0,
 Circle = 16,
 Square = 32,
 Triangle = 48,
};


}
