// automatically generated by the FlatBuffers compiler, do not modify

namespace InWorldz.Arbiter.Serialization
{

public enum ProfileShape : sbyte
{
 Circle = 0,
 Square = 1,
 IsometricTriangle = 2,
 EquilateralTriangle = 3,
 RightTriangle = 4,
 HalfCircle = 5,
};


}
